platform:ios,'7.0'
target "chatDemo-UI-xst" do
pod 'SDWebImage', '~> 3.7.6'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'AFNetworking', '~> 3.1.0'
pod 'HyphenateSDK', '~> 3.1.3'
pod 'SMSSDK', '~> 2.0.5'
pod 'MOBFoundation_IDFA'
pod 'IQKeyboardManager'
end
